version: "3.5"

services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./misc/conf/nginx-https.conf:/etc/nginx/sites-available/default
      - ./misc/ssl/server.crt:/etc/ssl/certs/server.crt
      - ./misc/ssl/server.key:/etc/ssl/private/server.key
      - ./certs:/root/certs
      - ./tgbot/static:/data/django/static
      - ./tgbot/media:/data/django/media
    command: bash -c "service nginx start && tail -f /dev/null"
    depends_on:
      - tgbot
      - ctree

  tgbot:
    build:
      context: tgbot
    command: bash -c "/code/manage.py collectstatic --no-input && python /code/manage.py migrate && /code/run/uwsgi.sh"
    volumes:
      - ./tgbot/static:/data/django/static
      - ./tgbot/media:/data/django/media
    depends_on:
      - db
    env_file:
      - tgbot/.env

  ctree:
    build:
      context: ctree
    command: bash -c "/code/manage.py collectstatic --no-input && python /code/manage.py migrate && /code/run/uwsgi.sh"
    volumes:
      - ./tgbot/static:/data/django/static
      - ./tgbot/media:/data/django/media
    depends_on:
      - db
    env_file:
      - ctree/.env

  celery:
    build:
      context: tgbot
    command: bash -c "cd /code && celery -A project worker -B -l info"
    volumes:
      - ./tgbot/static:/data/django/static
      - ./tgbot/media:/data/django/media
    depends_on:
      - tgbot
      - redis
    env_file:
      - tgbot/.env

  db:
    restart: always
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./misc/entrypoints/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    ports:
      - 5432:5432
  redis:
    restart: always
    image: redis:latest
    privileged: true
    command: redis-server


volumes:
  pgdata:
    name: tnt