version: "3.5"

services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./misc/conf/nginx-https.conf:/etc/nginx/sites-available/default
      - ./misc/ssl/server.crt:/etc/ssl/certs/server.crt
      - ./misc/ssl/server.key:/etc/ssl/private/server.key
      - ./certs:/root/certs
      - ./static:/data/django/static
      - ./media:/data/django/media
    command: bash -c "service nginx start && tail -f /dev/null"
    depends_on:
      - django
    env_file:
      - .env

  django:
    build:
      context: .
    command: bash -c "/code/manage.py collectstatic --no-input && python /code/manage.py migrate && /code/run/uwsgi.sh"
    volumes:
      - ./static:/data/django/static
      - ./media:/data/django/media
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build:
      context: .
    command: bash -c "cd /code && celery -A project worker -B -l info"
    volumes:
      - ./static:/data/django/static
      - ./media:/data/django/media
    depends_on:
      - django
    env_file:
      - .env

  db:
    restart: always
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    restart: always
    image: redis:latest
    privileged: true
    command: redis-server


volumes:
  pgdata:
    name: tnt