# Generated by Django 2.1.4 on 2018-12-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_urlparam_is_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcommand',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PATCH'), (4, 'DELETE')], default=1),
        ),
    ]
