# Generated by Django 2.1.4 on 2018-12-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20181212_0928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlParam',
            new_name='QueryParameter',
        ),
        migrations.AlterField(
            model_name='postparam',
            name='regex',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
