# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botcommand',
            name='answer_regex',
        ),
        migrations.RemoveField(
            model_name='postparam',
            name='type',
        ),
        migrations.AddField(
            model_name='postparam',
            name='regex',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postparam',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
