# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_auto_20170615_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlparam',
            name='is_header',
            field=models.BooleanField(default=False),
        ),
    ]
